
def build(bld):
    bld.stlib(target = 'optimizers', 
            source = 'opt.cpp gradient.cpp bfgs.cpp lbfgs.cpp linesearch.cpp',
            use='EIGEN',
            export_includes = ['.'])
    
    bld.shlib(target = 'optimizersDyn', 
            source = 'opt.cpp gradient.cpp bfgs.cpp lbfgs.cpp linesearch.cpp',
            use='EIGEN',
            export_includes = ['.'])
